---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prtdeployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: website-web-app
  template: 
    metadata:
      name: websitepod
      labels:
        app: website-web-app
    spec:
      containers:
      - name: websitecontainer
        image: zaidp/website-web-app
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: websitesvc
spec:
  type: NodePort
  selector:
    app: website-web-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
...
